"""add recipes table

Revision ID: 580b1391c7b6
Revises: eeebf876626e
Create Date: 2023-03-21 12:41:12.099968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580b1391c7b6'
down_revision = 'eeebf876626e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
