"""add reviews table

Revision ID: 273900d2a7c3
Revises: f0afe9ffb4dd
Create Date: 2023-03-21 12:45:57.771545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273900d2a7c3'
down_revision = 'f0afe9ffb4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
