"""add methods table

Revision ID: 94af2b305ad9
Revises: 968c2417061a
Create Date: 2023-03-21 14:40:52.203910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94af2b305ad9'
down_revision = '968c2417061a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('methods')
    # ### end Alembic commands ###
